name: Fluxo de Trabalho Python

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      fb_tok: ${{ secrets.fb_tok }}

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Instalar requests
      run: |
        python -m pip install requests

    - name: Executar script Python
      run: python main.py

